
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        env:
          node-version: '16.x'
        with:
          name: "jar"
          path: "${{ github.workspace }}/target/*.jar"


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        env:
          node-version: '16.x'
        with:
          name: "jar"
          path: "${{ github.workspace }}/target/"

      - name: directory check
        run : "ls -al ${{ github.workspace }}/target/"

